Kolay/Controllers/EventoController.cs
using System.Net;
using System.Web.Mvc;
using Kolay.Models;
using Kolay.DAL;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Web;
using System.IO;
using System.Web.Helpers;

namespace Kolay.Controllers
{
    [Authorize]
    public class EventoController : Controller
    {

        public ActionResult Avaliar(int? eventoId)
        {
            Evento evento = EventoDAO.BuscarEventoPorId(eventoId);
            ViewBag.Evento = evento;
            return View();
        }
        public ActionResult Historico(int? id)
        {
            return View(EventoDAO.BuscarEventoPorUsuario(id));
        }

        // GET: Evento
        public ActionResult Index(string id)
        {
            if (!String.IsNullOrEmpty(id))
            {
                return RedirectToAction("Pesquisar", new { id = id });
            }

            return View(EventoDAO.RetornarEventosPublico());
        }

        // GET: Evento
        public ActionResult Pesquisar(string id)
        {
            var eventos = EventoDAO.RetornarEventosPublico();

            if (!String.IsNullOrEmpty(id))
            {
                eventos = eventos.Where(s => s.Titulo.ToLower().Contains(id.ToLower())).ToList();
            }

            //foreach(Evento evento in eventos){
            //    evento.ResumoDescricao
            //}
            return View(eventos);
        }

        // GET: Evento/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evento evento = EventoDAO.BuscarEventoPorId(id);
            if (evento == null)
            {
                return HttpNotFound();
            }
            return View(evento);
        }

        // GET: Evento/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Evento/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EventoId,Titulo,Endereco,Descricao,MaximoParticipantes,Categoria,Privacidade,InicioEvento,FinalEvento,Organizador,BioOrganizador,Valor,DataCadastro,DataUltimaAlteracao")] Evento evento)
        {
            if (ModelState.IsValid)
            {
                if (Request.Files.Count <= 0)
                {
                    ModelState.AddModelError("", "Banner não foi informado");
                }
                else if (evento.InicioEvento.CompareTo(DateTime.Now) < 0)
                {
                    ModelState.AddModelError("", "Inicio do evento deve ser maior que a data atual");
                }
                else if (evento.InicioEvento.CompareTo(evento.FinalEvento) > 0)
                {
                    ModelState.AddModelError("", "Inicio do evento deve ser menor ou igual que o final do evento");
                }
                else
                {
                    evento.Usuario = UsuarioDAO.BuscarUsuarioPorId(Convert.ToInt32(User.Identity.Name));
                    evento.DataCadastro = DateTime.Now;
                    evento.EventoCancelado = 0;
                    evento.DataUltimaAlteracao = evento.DataCadastro;
                    evento.ResumoDescricao = evento.Descricao.Substring(0, evento.Descricao.Length >= 80 ? 80 : evento.Descricao.Length);

                    WebImage banner = WebImage.GetImageFromRequest();
                    if (banner != null)
                    {
                        var newFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(banner.FileName);
                        evento.BannerPath = @"\Images\" + newFileName;
                        banner.Save(@"~\" + evento.BannerPath);
                    }

                    if (EventoDAO.CadastrarEvento(evento))
                    {
                        ViewBag.SucessMessage = "registro criado com sucesso " + User.Identity.Name;
                        return RedirectToAction("Index");
                    }
                }
            }

            return View(evento);
        }
        public ActionResult EventoCancelado(int? id)
        {
            Evento evento = EventoDAO.BuscarEventoPorId(id);
            if (EventoDAO.Eventocancelado(evento))
            {
                foreach (var item in ParticipanteDAO.BuscarParticipantesPorEvento(id))
                {
                    /* EMAIL PARA USUARIOS DENTRO DO EVENTO CANCELADO */
                    EmailContract emailContract = new EmailContract();
                    emailContract.ToEmailAddress = item.Usuario.Email;
                    emailContract.Subject = "[Kolay] Evento Cancelado!";
                    emailContract.Body = "O evento <strong>" + item.Evento.Titulo + "</strong> no qual voce <strong>" + item.Usuario.Nome + "</strong> participava foi cancelado ! ";
                    emailContract.Body += "Obrigado por utilizar o Kolay. <br><br>Crie você também seu eventos conosco, visite kolay.com.br e crie seu evento hoje mesmo";
                    Singleton.Instance.EmailService.Send(emailContract);
                }
            }
            return View();
        }

        // GET: Evento/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evento evento = EventoDAO.BuscarEventoPorId(id);
            if (evento == null)
            {
                return HttpNotFound();
            }
            return View(evento);
        }

        // POST: Evento/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EventoId,Titulo,Endereco,Descricao,ResumoDescricao,MaximoParticipantes,Categoria,Privacidade,InicioEvento,FinalEvento,Organizador,BioOrganizador,Valor,DataCadastro,DataUltimaAlteracao")] Evento evento)
        {
            if (ModelState.IsValid)
            {
                Evento eventoAux = EventoDAO.BuscarEventoPorId(evento.EventoId);

                eventoAux.EventoId = evento.EventoId;
                eventoAux.Titulo = evento.Titulo;
                eventoAux.Endereco = evento.Endereco;
                eventoAux.Descricao = evento.Descricao;
                eventoAux.ResumoDescricao = evento.ResumoDescricao;
                eventoAux.MaximoParticipantes = evento.MaximoParticipantes;
                eventoAux.Categoria = evento.Categoria;
                eventoAux.Privacidade = evento.Privacidade;
                eventoAux.InicioEvento = evento.InicioEvento;
                eventoAux.FinalEvento = evento.FinalEvento;
                eventoAux.Organizador = evento.Organizador;
                eventoAux.BioOrganizador = evento.BioOrganizador;
                eventoAux.Valor = evento.Valor;
                eventoAux.DataUltimaAlteracao = evento.DataUltimaAlteracao;
                eventoAux.DataCadastro = evento.DataCadastro;

                if (EventoDAO.AlterarEvento(eventoAux))
                {
                    return RedirectToAction("Index");
                }
            }
            return View(evento);
        }

        // GET: Evento/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evento evento = EventoDAO.BuscarEventoPorId(id);
            if (evento == null)
            {
                return HttpNotFound();
            }
            return View(evento);
        }

        // POST: Evento/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Evento evento = EventoDAO.BuscarEventoPorId(id);
            if (EventoDAO.RemoverEvento(evento))
            {
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Erro ao remover evento.");
                return View(evento);
            }
        }
    }
}

Kolay/Controllers/ParticipanteController.cs
using System;
using System.Net;
using System.Web.Mvc;
using Kolay.Models;
using Kolay.DAL;
using System.Collections.Generic;

namespace Kolay.Controllers
{
    [Authorize]
    public class ParticipanteController : Controller
    {
        private static int? EventoId;

        // GET: Participante/ParticipantesEvento
        [Authorize]
        public ActionResult ParticipantesEvento(int? id)
        {
            if(id != null)
            {
                EventoId = id;
            }

            Evento evento = EventoDAO.BuscarEventoPorId(EventoId);

            if (evento != null)
            {
                ViewBag.Evento = evento;
                List<Participante> participantes = ParticipanteDAO.BuscarParticipantesPorEvento(EventoId);
                try
                {
                    participantes.Remove(ParticipanteDAO.BuscarParticipantePorUsuarioEvento(evento.EventoId, Convert.ToInt32(User.Identity.Name)));
                }
                finally { };
                
                return View(participantes);
            }

            ModelState.AddModelError("EKL001", "Ocorreu um inesperado. Informe ao administrador o código do erro.");
            return View();
        }

        // GET: Participante/Create
        [Authorize]
        public ActionResult Create(int? id)
        {
            Evento evento = EventoDAO.BuscarEventoPorId(id);

            if(evento != null)
            {
                EventoId = evento.EventoId;
                ViewBag.Evento = evento;
                Participante participante = new Participante() { Evento = evento };
                return View(participante);
            }

            ModelState.AddModelError("", "Ocorreu um erro ao fazer a inscrição. Tente novamente.");
            return View();
        }

        // POST: Participante/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ParticipanteId,DataInscricao,DataUltimaAlteracao")] Participante participante)
        {
            if (ModelState.IsValid)
            {
                participante.Evento = EventoDAO.BuscarEventoPorId(EventoId);
                participante.Usuario = UsuarioDAO.BuscarUsuarioPorId(Convert.ToInt32(User.Identity.Name));

                participante.DataInscricao = DateTime.Now;
                participante.DataUltimaAlteracao = participante.DataInscricao;
                if (ParticipanteDAO.InscreverParticipante(participante))
                {
                    /* Email de confirmação de inscrição */
                    EmailContract emailContract = new EmailContract();
                    emailContract.ToEmailAddress = participante.Usuario.Email;
                    emailContract.Subject = "[Kolay] Confirmação de inscrição em evento";
                    emailContract.Body = "Obrigado por se inscrever no evento <strong>" + participante.Evento.Titulo + "</strong>" +
                                    "que irá ocorrer em " + participante.Evento.InicioEvento + " no local " + participante.Evento.Endereco +
                                    "<br><br>";

                    if(participante.Evento.Valor > 0)
                    {
                        emailContract.Body += "No dia do evento deverá ser pago o valor de: R$ " + participante.Evento.Valor + "<br><br>";
                    }

                    emailContract.Body += "Obrigado por utilizar o Kolay. <br><br>Crie você também seu eventos conosco, visite kolay.com.br e crie seu evento hoje mesmo";

                    Singleton.Instance.EmailService.Send(emailContract);

                    /* Lembrete de evento */

                    DateTime epoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
                    emailContract.SendAt = (long) ((participante.Evento.InicioEvento.AddDays(-1) - epoch).TotalMilliseconds) / 1000;

                    long maxDateTime = (long) ((DateTime.Now.AddHours(72) - epoch).TotalMilliseconds) / 1000;
                    /* Não é permitido agendar email com mais de 72 horas */
                    if (emailContract.SendAt < maxDateTime)
                    {
                        emailContract.Subject = "[Kolay] Lembrete evento próximo";
                        emailContract.Body = "Seu evento <strong>" + participante.Evento.Titulo + "</strong>" +
                                        " irá ocorrer em breve (" + participante.Evento.InicioEvento + ") no local " + participante.Evento.Endereco +
                                        "<br> Não esqueça!!! <br><br>";

                        if (participante.Evento.Valor > 0)
                        {
                            emailContract.Body += "Lembre-se de levar o valor de: R$ " + participante.Evento.Valor + " referente a inscrição <br><br>";
                        }

                        emailContract.Body += "Obrigado por utilizar o Kolay. <br><br>Crie você também seu eventos conosco, visite kolay.com.br e crie seu evento hoje mesmo";

                        Singleton.Instance.EmailService.Send(emailContract);
                    }

                    ViewBag.SucessMessage = "Inscrição feita com sucesso";
                    return RedirectToAction("Index","Evento");
                }
                else
                {
                    ModelState.AddModelError("", "Ocorreu um erro ao fazer a inscrição. Tente novamente.");
                }
            }
            ViewBag.Evento = participante.Evento;
            return View(participante);
        }

        // GET: Participante/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Participante participante = ParticipanteDAO.BuscarParticipantePorId(id);
            if (participante == null)
            {
                return HttpNotFound();
            }
            return View(participante);
        }

        // POST: Participante/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Participante participante = ParticipanteDAO.BuscarParticipantePorId(id);
            if (ParticipanteDAO.RemoverParticipante(participante))
            {
                return RedirectToAction("Index", "Evento");
            }

            return View(participante);
        }
    }
}

Kolay/Views/Evento/Avaliar.cshtml
@using Kolay.Models;
@model Kolay.Models.Evento

@{
    ViewBag.Title = "Avaliar evento";
    Evento evento = ViewBag.Evento;
}

<div style="margin-top:70px;">
    <h1>Avaliar evento</h1>
</div>
<div style="margin-top:10px;width:100%;height:100%;display:flex;flex-direction:row;flex-wrap:wrap;justify-content:center;align-items:center;">
    <div style="text-align:center;width:500px">
        <h2>Detalhes do evento</h2>
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 style="margin:-5px">@evento.Titulo</h3>
            </div>
            <div class="panel-body">
                <h4>Organizador: @evento.Organizador</h4>
                <h4>Descrição: @evento.Descricao</h4>
                <h4>Local: @evento.Endereco</h4>
            </div>
        </div>
        <form class="form-horizontal">
            <fieldset>
                <legend> Defina uma nota para este evento:</legend>
                <div class="form-group">
                    <div style="text-align:left">
                        <div class="col-lg-10">
                            <div class="radio">
                                <label>
                                    <input type="radio" name="optionsRadios" id="optionsRadios1" value="noteEvento1">
                                    1 - Péssimo
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="optionsRadios" id="optionsRadios2" value="noteEvento2">
                                    2 - Ruim
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="optionsRadios" id="optionsRadios3" value="noteEvento3">
                                    3 - Regular
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="optionsRadios" id="optionsRadios4" value="noteEvento4">
                                    4 - Bom
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="optionsRadios" id="optionsRadios5" value="noteEvento5">
                                    5 - Ótimo
                                </label>
                            </div>
                        </div>
                        <div class="form-group" style="margin-left:50px">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label class="control-label" for="inputLarge">Comentário sobre o evento:</label>
                                    <input class="form-control input-lg" type="text" id="comentarioEvento">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
            <fieldset>
                <legend> Defina uma nota para o organizador do evento:</legend>
                <div class="form-group">
                    <div style="text-align:left">
                        <div class="col-lg-10">
                            <div class="radio">
                                <label>
                                    <input type="radio" name="optionsRadios" id="optionsRadios1" value="notaOrg1">
                                    1 - Péssimo
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="optionsRadios" id="optionsRadios2" value="notaOrg2">
                                    2 - Ruim
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="optionsRadios" id="optionsRadios3" value="notaOr3">
                                    3 - Regular
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="optionsRadios" id="optionsRadios4" value="notaOrg4">
                                    4 - Bom
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="optionsRadios" id="optionsRadios5" value="notaOrg5">
                                    5 - Ótimo
                                </label>
                            </div>
                        </div>
                        <div class="form-group" style="margin-left:50px">
                            <div class="col-lg-10">
                                <div class="form-group">
                                    <label class="control-label" for="inputLarge">Comentário sobre o organizador:</label>
                                    <input class="form-control input-lg" type="text" id="comentarioOrganizador">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
            <div class="form-group" style="width:100%;margin-left:-40px">
                <div class="col-lg-10 col-lg-offset-2">
                    <button type="submit" class="btn btn-default btn-lg btn-bloc">Avaliar</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Cancelar", "Index", "Home")
</div>


Kolay/Views/Evento/Details.cshtml
@model Kolay.Models.Evento

@{
    ViewBag.Title = "Detalhes do evento";
}


<div>
    <h4>Detalhes do evento</h4>
    <hr />
    <div style="margin-top:10px;width:100%;height:100%;display:flex;flex-direction:row;flex-wrap:wrap;justify-content:center;align-items:center;">
        <div class="panel panel-primary" style="width:0 auto">
            <div class="panel-heading">
                <h3 class="panel-title" style="text-align:center">
                    @Html.DisplayFor(model => model.Titulo)
                </h3>
            </div>
            <div class="panel-body">
                @Html.DisplayNameFor(model => model.Endereco) &mdash;
                @Html.DisplayFor(model => model.Endereco)<br /><br />
                @Html.DisplayNameFor(model => model.Descricao) &mdash;
                @Html.DisplayFor(model => model.Descricao)<br /><br />
                @Html.DisplayNameFor(model => model.MaximoParticipantes) &mdash;
                @Html.DisplayFor(model => model.MaximoParticipantes)<br /><br />
                @Html.DisplayNameFor(model => model.Categoria) &mdash;
                @Html.DisplayFor(model => model.Categoria)<br /><br />
                @Html.DisplayNameFor(model => model.Privacidade) &mdash;
                @Html.DisplayFor(model => model.Privacidade)<br /><br />
                @Html.DisplayNameFor(model => model.InicioEvento) &mdash;
                @Html.DisplayFor(model => model.InicioEvento)<br /><br />
                @Html.DisplayNameFor(model => model.FinalEvento) &mdash;
                @Html.DisplayFor(model => model.FinalEvento)<br /><br />
                @Html.DisplayNameFor(model => model.Organizador) &mdash;
                @Html.DisplayFor(model => model.Organizador) <br /><br />
                @Html.DisplayNameFor(model => model.BioOrganizador)&mdash;
                @Html.DisplayFor(model => model.BioOrganizador) <br /><br />
                @Html.DisplayNameFor(model => model.Valor) &mdash;
                @Html.DisplayFor(model => model.Valor)
            </div>
            @if (Model.Usuario.UsuarioId.Equals(Convert.ToInt32(User.Identity.Name)))
            {
                @Html.ActionLink("Cancelar Evento", "EventoCancelado", "Evento", new { id = Model.EventoId }, null)
            }
        </div>

    </div>
</div>

<div id="fb-root"></div>
<script>
    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.10';
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

<!-- Your share button code -->
<div class="fb-share-button"
     data-href="#"
     data-layout="button">
</div>


<p>
    @Html.ActionLink("Inscrever-se", "Create", "Participante", new { id = Model.EventoId }, null) |

    @Html.ActionLink("Voltar", "Index")
</p>

Kolay/Views/Evento/EventoCancelado.cshtml
@model Kolay.Models.Evento

@{
    ViewBag.Title = "EventoCancelado";
}

<div style="width:100%;margin-top:70px;pxheight:100%;display:flex;flex-direction:row;flex-wrap:wrap;justify-content:center;align-items:center;">
    <h2>Evento Cancelado com sucesso!</h2>
</div>

Kolay/Views/Evento/Historico.cshtml
@using Kolay.Extensions
@model IEnumerable<Kolay.Models.Evento>
@{
    ViewBag.Title = "Historico de eventos";
}

<div style="margin-top: 70px;">
    <h1>Historico de eventos participados</h1>
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-lg-3 col-md-4 col-sm-6 portfolio-item" style="margin-top: 10px">
                <div class="card h-100">
                    @Html.ActionImage("Details", "Evento", new { id = item.EventoId }, "~/Image/banner-evento.jpg", "BANNER PADRÃO", "card-img-top")
                    <div class="card-body">
                        <h4 class="card-title">
                            @Html.ActionLink(item.Titulo, "Details", new { id = item.EventoId })
                        </h4>
                        <p class="card-text">
                            @Html.DisplayFor(modelItem => item.Descricao)<br />
                            @if (item.FinalEvento >= DateTime.Now)
                            {
                                @Html.ActionLink("Avaliar", "Avaliar", "Evento", routeValues: null, htmlAttributes: new { eventoId = item.EventoId })
                            }
                        </p>
                    </div>
                    
                    @*<div class="card-footer">
                        <br />
                        @for (var i = 1; i <= 3; i++)
                        {
                            <span style="background-image:url('/Image/StarFade.gif');"></span>
                        }
                        @for (var i = (3 + 1); i <= 5; i++)
                        {
                            <span class="starFadeN"></span>
                        }
                    </div>*@
                </div>
            </div>
        }
    </div>
</div>




Kolay/Views/Evento/Index.cshtml
@model IEnumerable<Kolay.Models.Evento>

@{
    ViewBag.Title = "Eventos";
}
@using Kolay.Extensions
@Styles.Render("~/Content/Evento/4-col-portfolio.css")

<div class="container">
    <!-- Page Heading -->
    <h1 class="my-4">
        O QUE VOCÊ PROCURA PRA HOJE?
        <small>Temos de tudo aqui</small>
    </h1>
    <br/>

    <div class="row">
        @foreach (var item in Model)
        {
            if (item.EventoCancelado == 0)
            {
            <div class="col-lg-3 col-md-4 col-sm-6 portfolio-item" style="margin-top: 10px">
                <div class="card h-100">
                    @Html.ActionImage("Details", "Evento", new { id = item.EventoId }, "~/Images/banner-evento.jpg", "BANNER PADRÃO", "card-img-top")
                    <div class="card-body">
                        <h4 class="card-title">
                            @Html.ActionLink(item.Titulo, "Details", new { id = item.EventoId })
                        </h4>
                        <p class="card-text">
                            @Html.DisplayFor(modelItem => item.ResumoDescricao)
                        </p>
                    </div>
                    <div class="card-footer">
                        <br />
                        @if (Kolay.DAL.ParticipanteDAO.BuscarParticipantePorUsuarioEvento(item.EventoId, Convert.ToInt32(User.Identity.Name)) == null)
                        {
                            @Html.ActionLink("Inscrever-se", "Create", "Participante", new { id = item.EventoId }, null)
                        }
                        else
                        {
                            @Html.ActionLink("Ver participantes", "ParticipantesEvento", "Participante", new { id = item.EventoId }, null)
                        }

                    </div>
                </div>
            </div>
            }
        }
    </div>
</div>


Kolay/Views/Evento/Pesquisar.cshtml
@model IEnumerable<Kolay.Models.Evento>

@{
    ViewBag.Title = "Buscar eventos";
}
@using Kolay.Extensions
@Styles.Render("~/Content/Evento/4-col-portfolio.css")

<div class="container">
    <div class="row">
        <form role="search" class="navbar-form">
            <div class="form-group has-feedback">
                @using (Html.BeginForm("Pesquisar","Evento", FormMethod.Post))
                {
                    @Html.TextBox("id", "", new { @class = "form-control", placeholder = "Procurar eventos" })

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Pesquisar" class="btn btn-default" />
                        </div>
                    </div>
                }
            </div>
        </form>
    </div>
    <br />
    <div class="row">
        @foreach (var item in Model)
        {
            if (item.EventoCancelado == 0)
            {
            <div class="col-lg-3 col-md-4 col-sm-6 portfolio-item">
                <div class="card h-100">
                    @Html.ActionImage("Details", "Evento", new { id = item.EventoId }, (item.BannerPath != null ? "~/" + item.BannerPath : "~/Images/banner-evento.jpg"), "BANNER PADRÃO", "card-img-top")
                    <div class="card-body">
                        <h4 class="card-title">
                            @Html.ActionLink(item.Titulo, "Details", new { id = item.EventoId })
                        </h4>
                        <p class="card-text">
                            @Html.DisplayFor(ModelItem => item.ResumoDescricao)
                        </p>
                    </div>
                    <div class="card-footer">
                        <br />
                        @if (Kolay.DAL.ParticipanteDAO.BuscarParticipantePorUsuarioEvento(item.EventoId, Convert.ToInt32(User.Identity.Name)) == null)
                        {
                            @Html.ActionLink("Inscrever-se", "Create", "Participante", new { id = item.EventoId }, null)
                        }
                        else
                        {
                            @Html.ActionLink("Ver participantes", "ParticipantesEvento", "Participante", new { id = item.EventoId }, null)
                        }

                    </div>
                </div>
            </div>
            }
        }
    </div>
</div>
